### PR TITLE
Added required packages to use CloudArray

### PR DESCRIPTION
**Pull request by raphapr**
About CloudArray: https://github.com/gsd-ufal/cloudarray.jl

### CODE REVIEW

**Comment by tanmaykm** [comment]
Thanks!. Will put up the new image over the weekend.

**Comment by ViralBShah** [comment]
Shouldn't users wanting CloudArray install it themselves - since this is likely under heavy development?

**Comment by raphapr** [comment]
You're right @ViralBShah, my mistake. Should I submit another pull request?

**Comment by tanmaykm** [comment]
@raphapr please go ahead

**Pull request merged**
