### PR TITLE
fixup example notebooks

### LINKED ISSUE #211: Interact example update
As matplotlib uses global state for displaying plots using the pyplot api, a `clf()` is needed so the cell can be re-executed.

```julia
x = linspace(0,10,1000)
clf()
f = figure()
@manipulate for α = 1:0.1:4, β = 1:0.1:4, leg="a funny plot"
    withfig(f) do
        plot(x, cos(α*x + sin(β*x)))
        legend([leg])
    end
end
```

### PR DESCRIPTION
**Pull request by jakebolewski**
Closes #211, #209, #212.  I also deleted the skimage example as it does not currently work (skimage python package is not installed).

### CODE REVIEW

**Comment by tanmaykm** [comment]
Thanks!

**Comment by tanmaykm** [comment]
@jakebolewski does this address #209 ?

**Comment by jakebolewski** [comment]
No, #209 addresses that if I create a new notebook the default language for the notebook is Python and not Julia.

**Comment by tanmaykm** [comment]
Ok. #209 will probably be addressed once we update JuliaBox to use the latest Jupyter.
Thanks.

**Pull request merged**
